"use client";
import {useEffect,useState} from 'react';
import {FLOORS,validRoom,type Floor} from './signal';
const empty:Floor[]=FLOORS.map(floor=>({floor,count:0,names:[],updatedAt:null,state:'offline'}));
export default function Home(){
 const [room,setRoom]=useState(''),[floors,setFloors]=useState(empty),[selected,setSelected]=useState(1),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(location.search).get('room'),p=localStorage.getItem('floorwatch-room');const key=validRoom(q)?q:validRoom(p)?p:crypto.randomUUID().replaceAll('-','');localStorage.setItem('floorwatch-room',key);history.replaceState(null,'','/?room='+key);setRoom(key);},[]);
 useEffect(()=>{if(!room)return;let live=true;const controller=new AbortController();let busy=false;async function poll(){if(busy)return;busy=true;try{const r=await fetch('/api/floors?room='+room,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const data=await r.json() as {floors:Floor[]};if(live){setFloors(data.floors);setError('');}}catch{if(live){setError('서버 연결 실패 · 현재 수치를 확인할 수 없습니다.');setFloors(empty);}}finally{busy=false;}}void poll();const id=setInterval(()=>void poll(),2000);return()=>{live=false;controller.abort();clearInterval(id);};},[room]);
 const current=floors.find(f=>f.floor===selected)!;
 const total=floors.reduce((a,f)=>a+f.count,0),connected=floors.filter(f=>f.state!=='offline').length;
 const label=(f:Floor)=>f.state==='offline'?'연결 없음':f.count===0?'감지 없음':f.names.length?f.names.join(', '):'이름 미확인';
 return <main className="watch"><header className="watch-header"><a href={room?'/?room='+room:'/'} className="brand">FLOORWATCH<span>현장 모니터링</span></a><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/?room='+room);setCopied(true);}catch{setError('주소창의 링크를 직접 복사하세요.');}}} disabled={!room}>{copied?'복사 완료':'현황 링크 복사'}</button></header>
 <section className="watch-main"><div className="watch-intro"><div><p className="eyebrow">BUILDING A · LIVE MONITORING</p><h1>A동 작업 현황</h1><p>30층 개념 단면도 · 층별 카메라 1대 기준</p></div><a className="primary-link" href={'/camera?room='+room}>웹캠 연결하기 ↗</a></div>
 {error&&<p role="alert" className="error">{error}</p>}<div className="watch-stats"><article><span>현재 감지 인원</span><strong>{error?'—':total}<small>명</small></strong></article><article><span>사람 감지 층</span><strong>{error?'—':floors.filter(f=>f.count>0).length}<small>/ 30층</small></strong></article><article><span>신호 수신 층</span><strong>{error?'—':connected}<small>/ 30층</small></strong></article></div>
 <div className="watch-grid"><section className="tower-card"><div className="tower-title"><h2>A동 · 30층</h2><span>층 선택 → 상세 확인</span></div><div className="tower-roof"/><div className="tower">{floors.map(f=><button className={'tower-floor '+f.state+(selected===f.floor?' selected':'')} key={f.floor} onClick={()=>setSelected(f.floor)} aria-pressed={selected===f.floor}><b>{String(f.floor).padStart(2,'0')}F</b><span className="floor-names">{label(f)}</span><span>{f.state==='offline'?'—':'인원: '+f.count+'명'}</span></button>)}</div></section>
 <aside className="watch-detail"><p className="eyebrow">FLOOR DETAIL</p><h2>{selected}층</h2><span className={'status '+current.state}>{current.state==='offline'?'연결 없음':current.count?'사람 감지':'감지 없음'}</span><div className="detail-number">{current.state==='offline'?'—':current.count}<small>명</small></div><h3>이름표 판독 결과 · 실험</h3><p>{current.names.length?current.names.join(', '):'확인된 이름 없음'}</p><p className="muted">{current.count>current.names.length?'이름 미확인 '+(current.count-current.names.length)+'명':''}</p><hr/><p>담당 카메라 <b>CAM-{String(selected).padStart(2,'0')}</b></p><p>마지막 수신 <b>{current.updatedAt?new Date(current.updatedAt).toLocaleTimeString('ko-KR'):'기록 없음'}</b></p><div className="help-note">2초마다 갱신하며 12초간 신호가 없으면 연결 없음으로 표시합니다. 미연결 층은 사람이 없는 층을 뜻하지 않습니다.</div><div className="help-note">인원수는 현재 장면의 사람 검출 수입니다. 이름표 판독은 신원 확인이나 안전모 착용 판정이 아닙니다. 같은 사람이 여러 카메라에 잡히면 합계에 중복될 수 있습니다.</div></aside></div></section></main>;
}
